global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["192.168.50.101:9100", "192.168.50.100:9100", "176.9.44.19:9100"]


