---
all:
  hosts:
    old-friend:
      ansible_connection: ssh
      ansible_host: "10.0.0.2"
      ansible_port: 22
      ansible_user: "friend"
      ansible_ssh_user: "friend"
      ansible_ssh_private_key_file: id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_become_method: sudo
      admin_password: ''
