---
all:
  hosts:
    virtual-machine:
      ansible_connection: ssh
      ansible_host: "192.168.50.101"
      ansible_port: 22
      ansible_user: "friend"
      ansible_ssh_user: "friend"
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_become_method: sudo
